apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-persistent-storage
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: mgt-k8s-file-standard-delete
  resources:
    requests:
      storage: 10Gi
