apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-persistent-storage
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteMany
    # - ReadWriteOnce
  storageClassName: mgt-k8s-file-standard-delete-1001 # Needs to be mounted with mountOptions "uid=1001", "gid=1001".....
  resources:
    requests:
      storage: 4Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-persistent-storage
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mgt-k8s-disk-standard-delete
  resources:
    requests:
      storage: 4Gi
